backend_region    = "westeurope"
resource_region   = "switzerlandnorth"
RG                = "TEST_managed_via_TF"
backend_container = "tfstatefile"
backend_key       = "terraform.tfstate"
company           = "vhorvath2EPAM"
